apiVersion: v1
kind: Service
metadata:
  name: arc-api-v2
  labels:
    app: apic-ci-api
spec:
  type: NodePort
  selector:
    app: arc-api-v2
    tier: api
  ports:
  - port: 8080
    targetPort: 8080
