# Copyright 2019 Mulesoft.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

#
# Deployment configuration for application API
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-api-v2
  labels:
    app: apic-ci-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arc-api-v2
      tier: api
  template:
    metadata:
      labels:
        app: arc-api-v2
        tier: api
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: apic-ci-key
      containers:
      - name: apic-ci
        image: gcr.io/advancedrestclient-1155/arc-platform-api:0.1.0
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: PROJECT_ID
            value: advancedrestclient-1155
          - name: OAUTH2_CALLBACK
            value: https://api.advancedrestclient.com/auth/callback
          - name: OAUTH2_CLIENT_ID
            value: 1076318174169-ffof9prlf8nhehb8k2frhqa2890o50ao.apps.googleusercontent.com
          - name: MEMCACHE_URL
            value: 35.233.153.23:11211
